[package]
name = "poxymeter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
clap = { version = "3.0.0-beta.4" }
env_logger = { version = "0.9" }
hidapi = { version = "1.2" }
log = { version = "0.4.14" }
